FROM python:3.11-slim

WORKDIR /app

# Dependensi sistem
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh isi sync_worker
COPY . .

# Pastikan folder log tersedia
RUN mkdir -p /app/logs/sync

CMD ["python3", "-u", "sync_anggota.py"]
